package com.bawei.demo02.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.demo02.bean.CardItemEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CARD_ITEM_ENTITY".
*/
public class CardItemEntityDao extends AbstractDao<CardItemEntity, Void> {

    public static final String TABLENAME = "CARD_ITEM_ENTITY";

    /**
     * Properties of entity CardItemEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommodityId = new Property(0, String.class, "commodityId", false, "COMMODITY_ID");
        public final static Property CommodityName = new Property(1, String.class, "commodityName", false, "COMMODITY_NAME");
        public final static Property Count = new Property(2, String.class, "count", false, "COUNT");
        public final static Property Pic = new Property(3, String.class, "pic", false, "PIC");
        public final static Property Price = new Property(4, String.class, "price", false, "PRICE");
        public final static Property Checkboxstate = new Property(5, Boolean.class, "checkboxstate", false, "CHECKBOXSTATE");
    }


    public CardItemEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CardItemEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CARD_ITEM_ENTITY\" (" + //
                "\"COMMODITY_ID\" TEXT," + // 0: commodityId
                "\"COMMODITY_NAME\" TEXT," + // 1: commodityName
                "\"COUNT\" TEXT," + // 2: count
                "\"PIC\" TEXT," + // 3: pic
                "\"PRICE\" TEXT," + // 4: price
                "\"CHECKBOXSTATE\" INTEGER);"); // 5: checkboxstate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CARD_ITEM_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CardItemEntity entity) {
        stmt.clearBindings();
 
        String commodityId = entity.getCommodityId();
        if (commodityId != null) {
            stmt.bindString(1, commodityId);
        }
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(3, count);
        }
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(4, pic);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(5, price);
        }
 
        Boolean checkboxstate = entity.getCheckboxstate();
        if (checkboxstate != null) {
            stmt.bindLong(6, checkboxstate ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CardItemEntity entity) {
        stmt.clearBindings();
 
        String commodityId = entity.getCommodityId();
        if (commodityId != null) {
            stmt.bindString(1, commodityId);
        }
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(3, count);
        }
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(4, pic);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(5, price);
        }
 
        Boolean checkboxstate = entity.getCheckboxstate();
        if (checkboxstate != null) {
            stmt.bindLong(6, checkboxstate ? 1L: 0L);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CardItemEntity readEntity(Cursor cursor, int offset) {
        CardItemEntity entity = new CardItemEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // commodityId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // commodityName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // count
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pic
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // price
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // checkboxstate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CardItemEntity entity, int offset) {
        entity.setCommodityId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCommodityName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCount(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPrice(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCheckboxstate(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CardItemEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CardItemEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(CardItemEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
