package com.bawei.demo02.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.demo02.bean.CateGoryName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATE_GORY_NAME".
*/
public class CateGoryNameDao extends AbstractDao<CateGoryName, Void> {

    public static final String TABLENAME = "CATE_GORY_NAME";

    /**
     * Properties of entity CateGoryName.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CategoryName = new Property(0, String.class, "categoryName", false, "CATEGORY_NAME");
    }


    public CateGoryNameDao(DaoConfig config) {
        super(config);
    }
    
    public CateGoryNameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATE_GORY_NAME\" (" + //
                "\"CATEGORY_NAME\" TEXT);"); // 0: categoryName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATE_GORY_NAME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CateGoryName entity) {
        stmt.clearBindings();
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(1, categoryName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CateGoryName entity) {
        stmt.clearBindings();
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(1, categoryName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CateGoryName readEntity(Cursor cursor, int offset) {
        CateGoryName entity = new CateGoryName( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // categoryName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CateGoryName entity, int offset) {
        entity.setCategoryName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CateGoryName entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CateGoryName entity) {
        return null;
    }

    @Override
    public boolean hasKey(CateGoryName entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
