package com.bawei.demo02.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.demo02.bean.CardItemEntity;
import com.bawei.demo02.bean.CateGoryName;

import com.bawei.demo02.greendao.CardItemEntityDao;
import com.bawei.demo02.greendao.CateGoryNameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardItemEntityDaoConfig;
    private final DaoConfig cateGoryNameDaoConfig;

    private final CardItemEntityDao cardItemEntityDao;
    private final CateGoryNameDao cateGoryNameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardItemEntityDaoConfig = daoConfigMap.get(CardItemEntityDao.class).clone();
        cardItemEntityDaoConfig.initIdentityScope(type);

        cateGoryNameDaoConfig = daoConfigMap.get(CateGoryNameDao.class).clone();
        cateGoryNameDaoConfig.initIdentityScope(type);

        cardItemEntityDao = new CardItemEntityDao(cardItemEntityDaoConfig, this);
        cateGoryNameDao = new CateGoryNameDao(cateGoryNameDaoConfig, this);

        registerDao(CardItemEntity.class, cardItemEntityDao);
        registerDao(CateGoryName.class, cateGoryNameDao);
    }
    
    public void clear() {
        cardItemEntityDaoConfig.clearIdentityScope();
        cateGoryNameDaoConfig.clearIdentityScope();
    }

    public CardItemEntityDao getCardItemEntityDao() {
        return cardItemEntityDao;
    }

    public CateGoryNameDao getCateGoryNameDao() {
        return cateGoryNameDao;
    }

}
